In [1]:
import numpy as np 
import matplotlib.pylab as plt
from tqdm.auto import tqdm
from pint import UnitRegistry
%config InlineBackend.figure_format = 'retina'

In [2]:

def shrinkList(lst):
    tup_list = []
    i, index = 0, 0
    while(index < len(lst)):
        element_count = 0
        while(i < len(lst) and lst[i] == lst[index]):
            element_count += 1
            i += 1
        tup_list.append((lst[index], element_count))
        index += element_count
          
    return tup_list
def generalized_eig(A,eigen_val,multi):
    from scipy.linalg import null_space
    coef=A-eigen_val*np.eye(np.shape(A)[0])
    ns=null_space(np.linalg.matrix_power(coef,multi))
    M=np.zeros((np.shape(A)[0],multi))
    M[:,0]=ns[:,0].T
    for i in range(1,multi):
        eig=M[:,i-1]
        eig2=np.matmul(coef,eig)
        M[:,i]=eig2
    return M
def defective_eigenvec(A):
    omega, M = np.linalg.eig(A)
    shrink_eig=shrinkList(omega)
    eig_vec=np.zeros((np.shape(A)[0],1))
    for i in range(1,np.shape(shrink_eig)[0]+1):
        temp=generalized_eig(A,shrink_eig[i-1][0],shrink_eig[i-1][1])
        eig_vec=np.concatenate((eig_vec,temp),axis=1)
        eig_vec_trim=eig_vec[:,1:]
    return eig_vec_trim


In [3]:
AA=[[5,1,-2,4],[0,5,2,2],[0,0,5,3],[0,0,0,4]]
omega, M = np.linalg.eig(AA)
print(M)
np.linalg.inv(M)

[[ 1.00000000e+00 -1.00000000e+00  1.00000000e+00 -9.39618477e-01]
 [ 0.00000000e+00  1.11022302e-15 -1.11022302e-15  2.68462422e-01]
 [ 0.00000000e+00  0.00000000e+00  6.16297582e-31 -2.01346817e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  6.71156055e-02]]


array([[ 1.00000000e+00,  9.00719925e+14, -1.97032484e+15,
        -9.00719925e+15],
       [ 0.00000000e+00,  9.00719925e+14,  1.62259277e+30,
         4.86777830e+30],
       [ 0.00000000e+00,  0.00000000e+00,  1.62259277e+30,
         4.86777830e+30],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.48996644e+01]])

In [4]:
test=defective_eigenvec(AA)
print(test)
np.linalg.inv(test)

[[ 0.         -2.          2.          0.93961848]
 [ 0.          2.          0.         -0.26846242]
 [ 1.          0.          0.          0.20134682]
 [ 0.          0.          0.         -0.06711561]]


array([[  0.        ,   0.        ,   1.        ,   3.        ],
       [  0.        ,   0.5       ,   0.        ,  -2.        ],
       [  0.5       ,   0.5       ,   0.        ,   5.        ],
       [ -0.        ,  -0.        ,  -0.        , -14.89966443]])